name = "blawby-gmail-agent"
main = "src/index.ts"
compatibility_date = "2023-09-01"

# KV Namespace for storing OAuth tokens
kv_namespaces = [
  { binding = "OAUTH_TOKENS", id = "6ca8b80bce3a47efa90cfcef6b5a3121" }
]

# D1 Database for logging and analytics
# [[ d1_databases ]]
# binding = "DB"
# database_name = "blawby_agent_data"
# database_id = "placeholder-d1-id"

# Vectorize for semantic memory
# [[ vectorize ]]
# binding = "EMAIL_MEMORY"
# index_name = "email_embeddings"

# Cron Triggers for daily email processing
[triggers]
crons = ["0 0 * * *"] # Run once a day at midnight

# Environment variables
[vars]
DEBUG_MODE = "false" # Set to "true" for detailed logging

# Environment variables - these will be set via Cloudflare dashboard or CLI
# [vars]
# ENVIRONMENT = "development" 